Fix extension on so it's a valid file that works on Windows
There was a space on the end of the extension which fails to checkout on Windows

```
error: invalid path 'sites/handbook/source/handbook/support/workflows/ticketing_style_guide.md '
```